pdeljanov/Symphonia

sonata-codec-flac/src/validate.rs
sonata-core/Cargo.toml
sonata-core/src/audio.rs
sonata-core/src/io/buf_stream.rs
sonata-core/src/io/media_source_stream.rs
sonata-core/src/io/mod.rs
sonata-core/src/sample.rs

The reason i would want to use a decoder library in rust is for safety. This library uses a lot of unsafe. I removed some that were trivial to fix (and partially instantly UB).
Others i can not simply remove because its too deeply interwoven with other code, but to me seem to be UB. I added FIXME annotations to those.
Lastly there is some that look like they are fine, but are lacking comments on why they are actually safe. I added TODO annotations to those.
The main use of unsafe was to skip bounds checking on indexing and initializing arrays. Initializing 2 bytes big arrays on the stack costs literally nothing. Indexing can sometimes be avoided by using iterator (added some TODO notes there, too). In other cases please describe why it is actually safe to use unchecked indexing when you …

removed all trivial unsafe

---

sonata-play/src/main.rs

```rust
#[cfg(not(target_os = "linux"))]
fn play(_: Box<dyn FormatReader>, _: &DecoderOptions) -> Result<()> {
// TODO: Support the platform.
unsupported_error("Playback is not supported on your platform.")
}
```
Did not compile.

Fix build on non-linux

---

.gitignore
benchtest/benchtest.py

A selection of files in mp3, flac, and wav format are downloaded
from archive.org and benchmarking is perfomed by hyperfine.
Fixes issue #6

Script to run benchmark tests.

---

symphonia-core/src/audio.rs

Pretty sure it doesn't need &mut.

Change AudioPlanes::planes() to &self instead of &mut self

---

symphonia-format-isomp4/src/atoms/ftyp.rs
symphonia-format-isomp4/src/atoms/hdlr.rs
symphonia-format-isomp4/src/fourcc.rs

This removes the requirements that FourCC codes have to be readable ASCII and adds another track type `b"text"` to hdlr.
I encountered an `.m4a` file that reported its major brand as b"m4a\0" which also included this track type. I think It's legal according to the spec, but I'd have to double check this.

Add support for a few more atoms and components required for m4a files

---

.github/workflows/build.yml

This will build and test pull requests and the master branch when pushed to.
Note that `rustfmt` check is included, but since codebase is not formatted it is currently commented out. It would however be nice to format the code and include it, since manual formatting is a bit tedious and arbitrary.
You can see an example build of this here: https://github.com/udoprog/Symphonia/actions/runs/674345665
Fixes #11

Add GitHub actions workflow for testing builds

---

symphonia-core/src/io/media_source_stream.rs

Calling `Read::read_to_end` on a `MediaSourceStream` returns an UnexpectedEof instead of properly returning the read values. This is  particularly useful in unit tests. This PR fixes this issue.
Added unit tests to ensure this remains fixed.

Fix UnexpectedEof when using Read::read_to_end on MediaSourceStream

---

symphonia-core/src/codecs.rs
symphonia-core/src/formats.rs
symphonia-core/src/io/mod.rs
symphonia-core/src/meta.rs
symphonia-format-isomp4/src/demuxer.rs
symphonia-format-isomp4/src/stream.rs
symphonia-format-ogg/src/mappings/mod.rs

Resolves #24 
Similar to https://github.com/pdeljanov/Symphonia/pull/25, but this also requires `FormatReader` and `Decoder` to be `Send`.  The requirements for the other traits to be `Send` are all downstream effects of this. Per https://github.com/pdeljanov/Symphonia/issues/24#issuecomment-817185812, I need to keep a reference to the format reader and the decoder in a struct in order to keep playing the stream. The only other change here is switching an `Rc` to an `Arc`.

Require FormatReader and Decoder to be Send

---

symphonia-play/src/output.rs

Add `buffer_size` parameter to `cpal::StreamConfig`.

Fix symphonia-play compilation when using cpal

---

symphonia-bundle-flac/src/demuxer.rs
symphonia-bundle-mp3/src/demuxer.rs
symphonia-codec-aac/src/adts.rs
symphonia-core/src/formats.rs
symphonia-format-isomp4/src/demuxer.rs
symphonia-format-ogg/src/demuxer.rs
symphonia-format-wav/src/lib.rs

This adds a way to destroy the `FormatReader` and get access to the underlying stream. This is useful if you need to directly manipulate the stream and then restart playback. I'm working on integrating Symphonia with Rodio and this technique is used [here](https://github.com/RustAudio/rodio/blob/master/src/decoder/mod.rs#L262) to loop an audio source.

Add into_inner function to allow access to the stream

---

CONTRIBUTORS
symphonia-core/src/audio.rs

Reduces unsafe code by 50%! :upside_down_face: 
The unsafe code block in `chan_pair_mut` can be removed by using `split_at_mut`. In order to preserve the original behavior of the method, a conditional needs to be used to split using the correct index depending on the order of the channels (0,1 vs 1,0). However, the code could be reduced if the method were changed to require the channels be requested in ascending order (first < second). The method is always called in that manner, but I wasn't sure if the ability to get channels in other combinations might be necessary in the future.

Remove unsafe code in chan_pair_mut

---

CONTRIBUTORS
symphonia-play/src/output.rs

Minor change that replaces the deprecated PulseAudio format constant with the new one.

Replace deprecated constant in symphonia-play

---

CONTRIBUTORS
symphonia-core/src/probe.rs
symphonia-play/src/main.rs

When trying to use the library initially, it didn't seem clear that this would be empty all the time. It does make more sense if you read the `symphonia-player` example or look at the source, but it could probably gain from being more forward in the docs too.
Another idea: `ProbeResult` could be made into an enum instead, though this doesn't seem great and the docs are a simpler change since I don't think theres a real difference between the container being at the front of the stream and somewhere later after metadata, but I could be wrong there.
```rust
pub enum ProbeResult {
InitalContainer {
/// An instance of a `FormatReader` for the probed format.
format: Box<dyn FormatReader>,
},
Container {
/// An instance of a `FormatReader` for the probed format.
format: Box<dyn FormatReader>, …
```

Document when ProbeResult's metadata queue is empty

---

symphonia-bundle-flac/src/frame.rs
symphonia-format-ogg/src/mappings/flac.rs
symphonia-format-ogg/src/physical.rs
symphonia/fuzz/.gitignore
symphonia/fuzz/Cargo.toml
symphonia/fuzz/fuzz_targets/decode_any.rs

This, as-is, will try and fuzz all the default-enabled targets using the format guessing. This is *probably* good enough to not need one fuzzer target per format?

Add initial fuzzing harness

---

symphonia-bundle-flac/src/demuxer.rs
symphonia-bundle-mp3/src/demuxer.rs
symphonia-codec-aac/src/adts.rs
symphonia-core/src/formats.rs
symphonia-core/src/meta.rs
symphonia-core/src/probe.rs
symphonia-format-isomp4/src/atoms/ilst.rs
symphonia-format-isomp4/src/atoms/meta.rs
symphonia-format-isomp4/src/atoms/moov.rs
symphonia-format-isomp4/src/atoms/udta.rs
symphonia-format-isomp4/src/demuxer.rs
symphonia-format-ogg/src/demuxer.rs
symphonia-format-ogg/src/mappings/mod.rs
symphonia-format-wav/src/lib.rs
symphonia-metadata/src/id3v2/mod.rs
symphonia-play/src/main.rs

Hiya. When trying to bootstrap up a project with Symphonia I noticed an oddity/two with `MetadataQueue`. Its `pop()` method took an immutable reference, relying on the `RefCell` to get a mutable borrow, but the `push()` method took a mutable reference anyway. It seemed like an odd API disjoint, so I thought I'd try cleaning it up.
I chose to make `pop()` take a `&mut self` as well, to be consistent with most crates and to allow for the internals to be cleaned up. After that bit, there wasn't any need for the `RefCell` at all, so I removed it entirely. That also let me tweak `MetadataRef` to remove a panic, by just taking a regular reference.
In the end, `MetadataRef` seemed like it wasn't worth having anymore so I removed it in a separate commit. Happy to drop that if you think its too …

Make MetadataQueue's modification methods consistent

---

symphonia-play/src/output.rs

Fixes a type that didn't get changed when `WriteSample` was replaced with `RawSample`

Fix symphonia-play Windows build

---

.github/workflows/ci.yml

This follows up https://github.com/pdeljanov/Symphonia/pull/44 to fix a small issue I noticed while looking at addressing https://github.com/pdeljanov/Symphonia/issues/47.
Between a bit of misreading of the `cargo test` documentation and a lot of churn before I put my PR up, I accidentally used `--doc` for the only `--all-features` test, meaning the actual tests won't run.
Sorry for the PR churn :rip:

Run all the tests in CI

---

.github/workflows/ci.yml
symphonia-core/src/io/media_source_stream.rs
symphonia-core/src/io/mod.rs

The Cargo actions-rs package has a [nice hook-in](https://github.com/actions-rs/cargo#cross-compilation) for `cross`, which should let us run the tests on a big-endian architecture, in this case 32-bit PowerPC, pretty painlessly in CI.
This is currently based off https://github.com/pdeljanov/Symphonia/pull/48.
Closes #47

Run tests on PowerPC for big-endian coverage

---

symphonia-codec-opus/src/lib.rs

@pdeljanov, could you create another branch for Opus? The `opus` should be kept for reference for now. 
Part of the work for #8.
Porting over code from `opus` branch and verifying that it matches [RFC 7845](https://tools.ietf.org/pdf/rfc7845.pdf).

opus: handle identification header.

---

symphonia-codec-aac/src/aac.rs
symphonia-codec-aac/tests/tests.rs

This fixes an error when decoding an invalid aac file found by the fuzzer.
The panic was on channels, but I assume validation of the sample rate existing here is also needed.

AAC missing channel fix

---

symphonia-core/src/meta.rs

Every struct now has at least Clone and Debug with the exception of
Metadata<'a>. There might be more missing derives elsewhere but so far
this is the only part of the lib I've used directly.

Added missing Clone & Debug derives to core::meta

---

symphonia-core/src/codecs.rs
symphonia-core/src/formats.rs

I'm writing software where having these data types be debug-printable would be helpful. I see some other types got `Debug` impls recently, so I hope this can make it in, too!

Derive Debug for Cue, Track, CuePoint, CodecParameters, VerificationCheck

---

symphonia-core/src/meta.rs

Hi, this small PR derives `PartialEq` for the standard key metadata types. I'd like this for searching for a particular tag dynamically.

core: derive `PartialEq` for standard key types

---

symphonia-codec-vorbis/src/floor.rs
symphonia-core/src/codecs.rs
symphonia-core/src/formats.rs
symphonia-core/src/io/mod.rs
symphonia-core/src/meta.rs
symphonia-format-isomp4/src/stream.rs
symphonia-format-ogg/src/mappings/mod.rs

similar as https://github.com/pdeljanov/Symphonia/issues/24 just for impl sync trait.

Make FormatReader sync

---

CONTRIBUTORS
symphonia-metadata/src/id3v2/unsync.rs

Resolves #102 as discussed. Let me know if there are any other test cases I should account for, thanks!

Meta: Fix reading syncsafe integers with a bit width of 32

---

symphonia-bundle-mp3/src/layer3/hybrid_synthesis.rs

Move bounds checks out of the hot loop to be performed only once outside it. This should provide a modest performance boost, especially on CPUs with less powerful speculative execution.
Reduces the output of `cargo asm` for this function from 488 to 412 lines, when annotated with `#[inline(never)]` to make it easy to inspect.
<details>
<summary>Instruction counts before</summary>
125 movss
92 mov
85 lea
25 cmp
18 call
16 mulss
14 xor
14 jmp
13 addss
11 jne
6 ud2
6 push
6 pop
6 jae
5 jb
5 add
3 je
1 subss
1 sub
1 ret
</details>
<details>
<summary>Instruction counts after</summary>
125 movss
74 lea
68 mov
16 mulss
14 xor
14 jmp
14 cmp
13 addss
12 call
11 jne
6 push
6 pop
5 add
3 je
1 subss
1 sub
1 ret
</details>
This doesn't introduce any new panics - the code would have panicked anyway, …

MP3: move bounds checks out of the hot loop

---

symphonia-core/src/meta.rs

* Gets an immutable reference to the latest, and therefore newest, revision of the metadata.
Removes the need to pop though the revisions via a loop when all you want is the latest.
As mentioned in https://github.com/librespot-org/librespot/pull/967

Add `latest` function to Metadata

---

symphonia-format-ogg/src/mappings/opus.rs

This allows users to convert seek results for Ogg Opus files given in `TimeStamp`s back into `Time`s without having to track special cases.

ogg: Apply TimeBase to contained Opus streams

---

symphonia-format-isomp4/src/atoms/ilst.rs

The standard tag used was `Artist` when it should be `SortArtist`.

isomp4: Fix incorrect parsing of SortArtist

---

symphonia-core/src/audio.rs

Allows mutable access to exported samples, enabling in-place processing of output audio data.
Currently, to use functions like libopus's soft_clip (which take `&mut [f32]`, interleaved) this can only be achieved on `SampleBuffer` with a significant memcopy (seemingly ~8us for 1920 `f32` samples, relative to ~40us decode + ~80us encode). `samples_mut` removes this additional overhead.

core: Add `SampleBuffer::samples_mut`

---

symphonia-format-mkv/src/demuxer.rs
symphonia-format-mkv/src/ebml.rs

Read-only sources were mistakenly calling `Seek::seek` if an MkvReader's `clusters` had been populated, causing a seek error even if the target timestamp occurs later in the stream.
This PR changes the EBML iterator to consume bytes if the source is not seekable *and* the destination can be forward-skipped to, otherwise returning `ForwardOnly`.

mkv: Fix forward seeks with read-only MediaSources

---

symphonia-metadata/src/vorbis.rs

Some .flac files downloaded from Bandcamp have the `UNSYNCEDLYRICS` tag set if the artist added lyrics to a track.  This PR enables Symphonia to also read this tag for lyrics metadata.

meta: use unsyncedlyrics vorbis tag for lyrics

---

symphonia-format-wav/src/chunks.rs

This PR contains a work around for some WAV files that have an incorrect channel mask value. For example VLC can still play them.

Handle incorrect channel mask in WAV files

---

symphonia-core/src/meta.rs

This would come very handy when trying to get the value of a standard tag or visual multiple times, allowing for instance to build a `HashMap<StandardTagKey, Value>` and fetching from it instead of having to rely on a `&[Tag]` which requires iteration for each search.

Make StandardTag{Key,Visual} implement Hash

---

GETTING_STARTED.md

I found a small inconsistency in variable names in this example, so I fixed it.

Fix inconsistency in GETTING_STARTED.md

---

symphonia-format-ogg/src/mappings/opus.rs

I implemented this because buffering some ogg web streams seemed to hang trying to buffer up 1s of data. Turns out it was opus and the durations of all opus packets were demuxed as 0. I think I implemented this correctly but don't take my word for it. Maybe it could be of use?

ogg: Decode opus packet durations

---

symphonia-format-riff/src/wave/chunks.rs
symphonia-format-wav/src/chunks.rs

Example ambisonic wav files can be found here: https://www.ambisonia.com/

wav: add ambisonic bformat subtypes

---

symphonia-bundle-flac/src/demuxer.rs
symphonia-bundle-mp3/src/demuxer.rs
symphonia-bundle-mp3/src/lib.rs
symphonia-check/src/main.rs
symphonia-codec-aac/src/adts.rs
symphonia-codec-aac/tests/tests.rs
symphonia-core/src/formats.rs
symphonia-core/src/io/media_source_stream.rs
symphonia-core/src/probe.rs
symphonia-format-caf/src/chunks.rs
symphonia-format-caf/src/demuxer.rs
symphonia-format-isomp4/src/demuxer.rs
symphonia-format-mkv/src/demuxer.rs
symphonia-format-ogg/src/demuxer.rs
symphonia-format-ogg/src/physical.rs
symphonia-format-riff/src/aiff/chunks.rs
symphonia-format-riff/src/aiff/mod.rs
symphonia-format-riff/src/common.rs
symphonia-format-riff/src/wave/chunks.rs
symphonia-format-riff/src/wave/mod.rs
symphonia-metadata/src/id3v2/mod.rs
symphonia-play/src/main.rs
symphonia/src/lib.rs

This allows reading data from borrowed buffers and such.
This is a breaking change, because it adds many lifetimes in codebase.
Closes #117

Allow non-static sources

---

symphonia-format-isomp4/src/atoms/trak.rs
symphonia-format-isomp4/src/demuxer.rs
symphonia-format-isomp4/src/stream.rs

trak.mdia.mdhd.duration sometimes is 0 for fragmented mp4.
There are two files from Dolby Vision for which video packets cannot be extracted because of that:
- iOS_P5_GlassBlowing2_3840x2160@59.94fps_15200kbps.mp4
- P81_GlassBlowing2_3840x2160@59.94fps_15200kbps_fmp4.mp4
Solution: take duration from trak.tkhd.duration
Please review.

isomp4: fix zero track duration for fragmented mp4

---

symphonia-common/src/mpeg/mod.rs
symphonia-common/src/mpeg/video/mod.rs
symphonia-format-isomp4/src/atoms/avcc.rs
symphonia-format-mkv/src/codecs.rs

extract video decoder configuration parsing into common, for future reuse

common: Move video config box parsers to common

---

symphonia-core/src/codecs/audio.rs
symphonia-core/src/codecs/subtitle.rs
symphonia-core/src/codecs/video.rs
symphonia-core/src/formats/mod.rs
symphonia-format-isomp4/src/atoms/esds.rs
symphonia-format-isomp4/src/atoms/stsd.rs

Using CODEC_ID_NULL from both audio and video in the same file is not quite convenient and  requires prefixes.
Unique names also remove c-bindings errors

core: rename CODEC_ID_NULL and other constants to be unique

---

symphonia-common/src/mpeg/video/mod.rs
symphonia-core/src/codecs/video.rs
symphonia-format-isomp4/src/atoms/alac.rs
symphonia-format-isomp4/src/atoms/avcc.rs
symphonia-format-isomp4/src/atoms/dac3.rs
symphonia-format-isomp4/src/atoms/dec3.rs
symphonia-format-isomp4/src/atoms/dovi.rs
symphonia-format-isomp4/src/atoms/esds.rs
symphonia-format-isomp4/src/atoms/flac.rs
symphonia-format-isomp4/src/atoms/hvcc.rs
symphonia-format-isomp4/src/atoms/mod.rs
symphonia-format-isomp4/src/atoms/opus.rs
symphonia-format-isomp4/src/atoms/stsd.rs
symphonia-format-isomp4/src/atoms/wave.rs
symphonia-format-mkv/src/codecs.rs
symphonia-format-mkv/src/element_ids.rs
symphonia-format-mkv/src/segment.rs

it is based on constants renaming commit from PR #322
This PR is to get early feedback, mkv changes are not finished, I will add another commit later
Notes: 
- used let mut VideoCodecParameters and write values directly into it, instead of creating many temp variables and then copy them to VideoCodecParameters. This is not following other code pattern, but with the growing number of variables can be more suitable/readable. Please let me know your opinion.
- removed VisualCodecSpecific, initially this followed AudioCodecSpecific, but I'm not sure it is needed. VideoCodecParameters should have codec_id_tag (FourCC code) where VisualCodecSpecific variations can be stored.

Convert VideoCodecParameters.extra_data to vector

---

symphonia-bundle-flac/src/frame.rs

Fixes #293
Convert the value 192 to 192_000.
Without this conversion, the FLAC parser’s resync() method cannot find a valid frame and attempts to seek beyond the file size, causing an “unexpected end of file” error."

flac: normalize the frame's sample rate when reading it from a single byte

---

symphonia-format-riff/src/aiff/chunks.rs
symphonia-format-riff/src/wave/chunks.rs

should fix builds for other PRs.

riff: fix clippy warnings, fix overflow with u16 for frames_per_block calculation

---

symphonia-codec-adpcm/src/lib.rs

adpcm: report unsupported error for more than 2 channels

---

symphonia-codec-alac/src/lib.rs

alac: validate mid_side_shift to not overflow

---

symphonia-core/src/io/buf_reader.rs

This addresses out-of-memory errors mentioned in the following comment: https://github.com/pdeljanov/Symphonia/issues/301#issuecomment-2569727809.
Issue description:
For a big buffer where the pattern was not found at the end, the reader advanced its position to the end of the buffer.
For a buffer smaller than the pattern length, the reader did not advance its position and entered into infinite loop while reading tags.
This commit ensures that the reader's position is always advanced, resolving the issue.

core: advance reader's position if pattern cannot be found, fixes out of memory from #301

---

symphonia-format-mkv/src/ebml.rs

Declaring a constant for EbmlElementHeader<EbmlSchema> doesn't allow to use EbmlElementHeader::MIN_SIZE without specifying the scheme which I considered too complex for a constant. I can define it globally in the file or inside the Schema if you want.  Currently it is a 2 with a comment
I added skipping of a byte to put reader position to the end of parent. Does it make sense, taking into consideration that it will be skipped later anyway?
For element header seeking I propose to rewind the stream to the `parent_end` vs `header.pos`, which should be similar to as everything was ok. Let me know your preference.

mkv: detect parent overrun after the header parsing

---

symphonia-format-isomp4/src/demuxer.rs

Changed the MIME type from "audio/m4a" to "audio/mp4" in the format descriptor, as audio/mp4 is the standard MIME type for MPEG-4 audio files according to IANA specifications.

fix(isomp4): Update MIME type for m4a files to audio/mp4

---

symphonia-codec-aac/src/aac/cpe.rs
symphonia-codec-aac/src/aac/ics/mod.rs
symphonia-codec-aac/src/adts.rs

refactored aac aproximate_frame_count() method. It had some issues which causes panic. Should fix cases from https://github.com/qarmin/Automated-Fuzzer/actions/runs/12516290494 (REPORTS___SYMPHONIA*)
1. renamed total_len to remaining_len because this is not the length of the whole file, but it was considered such in some places.
2. first sample point to start from the beginning, file can contain a single frame
3. check step to be bigger than 0 to avoid panic
4. skip the rest of the frame after the header is read to avoid looking for sync word in the audio data
5. break if reading 100 frames overlap next sample point
I haven't tested on VBR aac to observe any improvements, It was https://github.com/pdeljanov/Symphonia/issues/196#issuecomment-1960507107that approximate method is not perfect …

aac: refactor approximate frame count, fuzzy fixes

---

symphonia-bundle-flac/src/frame.rs

This PR is a backport of #328 from the `dev-0.6` branch; hopefully this is trivial enough to include in the next 0.5.x release.
Resolves #275.

flac: normalize the frame's sample rate when reading it from a single byte (backport #328)

---

symphonia-core/src/io/buf_reader.rs

fixes #379
This PR backports 0.6-only commit 31f3ffa586f5262d79ee8d6d7c6a34346a03bee5(#344) to 0.5.x (master) to fix the memory leak mentioned in #379.
I dont *think* there is a "merge block for master and divert everything to 0.6", so i hope this can be merged before 0.6, which does (to my knowledge) not have any release date (or anytime too soon).
If this PR is not merged before or not released for a 0.5.x release, it can be closed without being merged. (i hope to get it into symphonia `0.5.5` as specified in #330)
@sscobici are you ok with the way this is backported?

Backport 0.6 memory leak fix to 0.5.x

---

symphonia-core/src/util.rs

Since version 1.46.0, the language natively supports [trailing_ones](https://doc.rust-lang.org/std/primitive.u32.html#method.trailing_ones) for all primitive integer types.
The manual implementations can be removed from the bit manipulation utilities.

core (util): Remove redundant trailing_ones.

---

symphonia-core/src/formats.rs

This is useful to be able to do:
```rust
if seek_mode == SeekMode::Accurate { ... }
```
instead of the less readable:
```rust
if matches!(seek_mode, SeekMode::Accurate) { ... }
```
Ran into this as we're improving sample-accurate seeking in Rodio: https://github.com/RustAudio/rodio/pull/697

feat: derive Eq and PartialEq for SeekMode

---

symphonia-format-mkv/src/codecs.rs

The mkv demuxer already supports parsing the channel information, but it wasn't being added to the codec params. According to the [spec](https://www.matroska.org/technical/elements.html), there was a `ChannelPositions` element used to denote the channel positions, but it's [listed as reclaimed](https://datatracker.ietf.org/doc/draft-ietf-cellar-matroska/21/) (not in use), so I'm not sure if there's a defined way to map the specific channel positions. 
Please let me know if I missed anything. Thanks!

mkv: include channels in codec params

---

symphonia-core/src/formats.rs

I have a problem with this [file](https://drive.google.com/file/d/1_ndRi_iRIhb83RmjJAjCWQAohxRBuLRK/view?usp=sharing) , the code will panic if seeking near the end of file.
For example that file have 28800000 sample, and if I seek to 28799999 it will panic because the index search function will return the upper with 0 byte_offset, so the end_byte_offset will become less than start_byte_offset, so the code will panic because of underflow.

Fix seeking on some flac file: Ignore seek points if n_frames is 0
